import request from '@/utils/request'

// ============ 客户管理 ============
export const getCustomerList = (params) => request.post('/customer/list', params)
export const getCustomerDetail = (id) => request.get(`/customer/detail/${id}`)
export const addCustomer = (data) => request.post('/customer/add', data)
export const updateCustomer = (data) => request.post('/customer/update', data)
export const deleteCustomer = (id) => request.post('/customer/delete', { id })
export const claimCustomer = (id) => request.post('/customer/claim', { id })
export const assignCustomer = (data) => request.post('/customer/assign', data)
export const batchAssignCustomer = (data) => request.post('/customer/batch-assign', data)
export const convertCustomer = (data) => request.post('/customer/convert', data)
export const importCustomers = (formData) => request.post('/customer/import', formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const exportCustomers = (params) => request.post('/customer/export', params, { responseType: 'blob' })
export const addContact = (data) => request.post('/customer/contact/add', data)
export const updateContact = (data) => request.post('/customer/contact/update', data)
export const deleteContact = (id) => request.post('/customer/contact/delete', { id })
export const getSalesUsers = () => request.get('/customer/sales-users')
export const getMySubordinates = () => request.get('/customer/my-subordinates')
export const getCustomer360 = (id) => request.get(`/customer/${id}/360`)
export const releaseCustomer = (customerId) => request.post('/customer/release', { customer_id: customerId })
export const getAssignRules = () => request.get('/customer/assign-rules')
export const createAssignRule = (data) => request.post('/customer/assign-rules/create', data)
export const updateAssignRule = (data) => request.post('/customer/assign-rules/update', data)
export const deleteAssignRule = (id) => request.post('/customer/assign-rules/delete', { id })
export const getLeadsList = (params) => request.post('/customer/leads/list', params)
export const convertLead = (id) => request.post('/customer/leads/convert', { id })
export const claimLead = (id) => request.post('/customer/leads/claim', { id })
export const markLeadLost = (id) => request.post('/customer/leads/mark-lost', { id })
export const getLeadsStats = () => request.get('/customer/leads/stats')
export const batchClaimCustomer = (ids) => request.post('/customer/batch-claim', { ids })
export const autoAssignCustomer = (data) => request.post('/customer/auto-assign', data)
export const getCustomerTemplate = () => request.get('/customer/template')
export const qualityCheck = (data) => request.post('/customer/quality-check', data)
export const qualityReport = (data) => request.post('/customer/quality-report', data)
export const importPreview = (data) => request.post('/customer/import-preview', data)
export const importConfirm = (data) => request.post('/customer/import-confirm', data)
export const calculateCustomerScore = (id) => request.post(`/scoring/calculate/${id}`)

// ============ 跟进记录 ============
export const getFollowUpList = (customerId, params = {}) => request.post('/follow-up/list', { customer_id: customerId, ...params })
export const addFollowUp = (data) => request.post('/follow-up/add', data)
export const updateFollowUp = (data) => request.post('/follow-up/update', data)
export const deleteFollowUp = (id) => request.post('/follow-up/delete', { id })
export const getFollowPlanList = (customerId) => request.post('/follow-plan/list', { customer_id: customerId })
export const addFollowPlan = (data) => request.post('/follow-plan/add', data)
export const completeFollowPlan = (id) => request.post('/follow-plan/complete', { id })
export const cancelFollowPlan = (data) => request.post('/follow-plan/cancel', data)
export const getFollowupTemplates = () => request.get('/followup-templates')
export const saveFollowupTemplate = (data) => request.post('/followup-templates', data)
export const deleteFollowupTemplate = (id) => request.delete(`/followup-templates/${id}`)
export const getFollowUpCalendar = (params) => request.post('/follow-up/calendar', params)
export const getTodayReminders = () => request.get('/follow-up/remind')
export const getTomorrowTasks = () => request.get('/follow-up/tomorrow')
export const getFollowUpPlans = () => request.get('/follow-up/plans')
export const batchAddFollowUp = (items) => request.post('/follow-up/batch-add', { items })
export const getFollowUpTaskStats = () => request.get('/follow-up/task-stats')

// ============ 商机管理 ============
export const getOpportunityList = (params) => request.post('/opportunity/list', params)
export const addOpportunity = (data) => request.post('/opportunity/add', data)
export const updateOpportunity = (data) => request.post('/opportunity/update', data)
export const deleteOpportunity = (id) => request.post('/opportunity/delete', { id })
export const updateOpportunityStage = (id, stage) => request.post('/opportunity/update-stage', { id, stage })
export const getSalesFunnel = (params) => request.get('/opportunity/funnel', { params })
export const getOpportunityDetail = (id) => request.get(`/opportunity/detail/${id}`)
export const getOpportunityStageLog = (id) => request.get(`/opportunity/stage-log/${id}`)
