import request from '@/utils/request'

// ============ 客户管理（Phase 5：切换到独立 /customers 端点） ============
// 旧 /customer/* 端点保留为兼容层，内部调用相同 controller 方法
// 全量客户列表（兼容旧 /customer/list 端点）
export const getCustomerList = (params) => request.post('/customers/list', params)
// 正式客户列表（status IN following/quoted/negotiating/signed）
export const getFormalCustomers = (params) => request.post('/customers', params)
export const getCustomerDetail = (id) => request.get(`/customers/detail/${id}`)
export const addCustomer = (data) => request.post('/customers/add', data)
export const updateCustomer = (data) => request.post('/customers/update', data)
export const deleteCustomer = (id) => request.post('/customers/delete', { id })
export const assignCustomer = (data) => request.post('/customer/assign', data)
export const batchAssignCustomer = (data) => request.post('/customer/batch-assign', data)
export const forwardCustomer = (data) => request.post('/customers/forward', data)
export const backwardCustomer = (data) => request.post('/customers/backward', data)
export const exportCustomers = (params) => request.post('/customers/export', params, { responseType: 'blob' })
export const addContact = (data) => request.post('/customer/contact/add', data)
export const updateContact = (data) => request.post('/customer/contact/update', data)
export const deleteContact = (id) => request.post('/customer/contact/delete', { id })
export const getSalesUsers = () => request.get('/customer/sales-users')
export const getMySubordinates = () => request.get('/customer/my-subordinates')
export const getCustomer360 = (id) => request.get(`/customer/${id}/360`)
export const releaseCustomer = (customerId) => request.post('/customer/release', { customer_id: customerId })
export const getAssignRules = () => request.get('/customer/assign-rules')
export const createAssignRule = (data) => request.post('/customer/assign-rules/add', data)
export const updateAssignRule = (data) => request.post('/customer/assign-rules/update', data)
export const deleteAssignRule = (id) => request.post('/customer/assign-rules/delete', { id })
export const getCustomerTemplate = () => request.get('/customer/template')
export const importPreview = (data) => request.post('/customer/import-preview', data)
export const importConfirm = (data) => request.post('/customer/import-confirm', data)
export const calculateCustomerScore = (id) => request.post(`/scoring/calculate/${id}`)

// ============ 跟进记录 ============
export const getFollowUpList = (customerId, params = {}) => request.post('/follow-up/list', { customer_id: customerId, ...params })
export const addFollowUp = (data) => request.post('/follow-up/add', data)
export const updateFollowUp = (data) => request.post('/follow-up/update', data)
export const deleteFollowUp = (id) => request.post('/follow-up/delete', { id })
export const getFollowupTemplates = () => request.get('/followup-templates')
export const saveFollowupTemplate = (data) => request.post('/followup-templates', data)
export const deleteFollowupTemplate = (id) => request.delete(`/followup-templates/${id}`)
export const getFollowUpCalendar = (params) => request.post('/follow-up/calendar', params)
export const getTodayReminders = () => request.get('/follow-up/remind')
export const getTomorrowTasks = () => request.get('/follow-up/tomorrow')
export const getFollowUpPlans = (params = {}) => request.post('/follow-up/plan/list', params)
export const addFollowUpPlan = (data) => request.post('/follow-up/plan/add', data)
export const completeFollowUpPlan = (data) => request.post('/follow-up/plan/complete', data)
export const cancelFollowUpPlan = (data) => request.post('/follow-up/plan/cancel', data)
export const batchAddFollowUp = (items) => request.post('/follow-up/batch-add', { items })
export const getFollowUpTaskStats = () => request.get('/follow-up/task-stats')
export const getOverdueCustomers = (params) => request.get('/customer/overdue', { params })
export const getNearRecycleCustomers = (params) => request.get('/customer/near-recycle', { params })

// ============ 商机管理 ============
export const getOpportunityList = (params) => request.post('/opportunity/list', params)
export const addOpportunity = (data) => request.post('/opportunity/add', data)
export const updateOpportunity = (data) => request.post('/opportunity/update', data)
export const deleteOpportunity = (id) => request.post('/opportunity/delete', { id })
export const updateOpportunityStage = (id, stage) => request.post('/opportunity/update-stage', { id, stage })
export const getSalesFunnel = (params) => request.get('/opportunity/funnel', { params })
export const getOpportunityDetail = (id) => request.get(`/opportunity/detail/${id}`)
export const getOpportunityStageLog = (id) => request.get(`/opportunity/stage-log/${id}`)
