import request from '@/utils/request'

export const getEmailList = (params) => request.get('/email/list', { params })
export const sendEmail = (data) => request.post('/email/send', data)
export const getEmailAccounts = () => request.get('/email/accounts')
export const addEmailAccount = (data) => request.post('/email/account', data)
export const updateEmailAccount = ({ id, ...data }) => request.put(`/email/account/${id}`, data)
export const deleteEmailAccount = (id) => request.delete(`/email/account/${id}`)
export const syncEmails = (accountId) => request.post(`/email/sync/${accountId}`)
export const getEmailStats = () => request.get('/email/stats/overview')
export const markEmailRead = (id) => request.put(`/email/${id}/read`)
export const getEmailDetail = (id) => request.get(`/email/${id}`)
export const toggleEmailStar = (id) => request.put(`/email/${id}/star`)
export const linkCustomerToEmail = (id, customerId) => request.post(`/email/${id}/link-customer`, { customer_id: customerId })
export const testEmailAccount = (id) => request.post(`/email/account/${id}/test`)
