import request from '@/utils/request'

export const getReportSalesFunnel = (params) => request.get('/report/sales-funnel', { params })
export const getReportPayment = (params) => request.get('/report/payment', { params })
export const getReportPerformance = (params) => request.get('/report/performance', { params })
export const getReportCustomerAnalysis = (params) => request.get('/report/customer-analysis', { params })
export const getReportOverview = () => request.get('/report/overview')
export const getReportDashboardStats = () => request.get('/report/dashboard-stats')
export const getReportBusiness = (params) => request.get('/report/business', { params })
export const getReportFinance = (params) => request.get('/report/finance', { params })
export const getReportOverdue = (params) => request.post('/report/overdue', params)
export const getReportOverdueStats = () => request.get('/report/overdue-stats')
export const getReportTodayTasks = () => request.get('/report/today-tasks')
export const getReportQuickStats = () => request.get('/report/quick-stats')
export const getReportPurchaseTrend = (params) => request.get('/report/purchase-trend', { params })
export const getReportPurchaseBySupplier = (params) => request.get('/report/purchase-by-supplier', { params })
export const getReportSalesTrend = (params) => request.get('/report/sales-trend', { params })
export const getReportCustomList = () => request.get('/report/custom')
export const createReportCustom = (data) => request.post('/report/custom', data)
export const updateReportCustom = (id, data) => request.put(`/report/custom/${id}`, data)
export const deleteReportCustom = (id) => request.delete(`/report/custom/${id}`)
export const runReportCustom = (id, params) => request.post(`/report/custom/${id}/run`, params)
export const getReportCustomFields = (source) => request.get(`/report/custom/fields/${source}`)
export const getReportCustomer = (params) => request.get('/report/customer', { params })
export const exportReport = (params) => request.post('/report/export', params, { responseType: 'blob' })
