import request from '@/utils/request'

// ============ 审批管理 ============
export const getMyPending = () => request.get('/approval/my-pending')
export const getMySubmitted = () => request.get('/approval/my-submitted')
export const getApprovalDetail = (type, id) => request.get(`/approval/detail-with-history/${type}/${id}`)
export const approveRequest = (id, remark) => request.post('/approval/approve', { id, remark })
export const rejectRequest = (id, remark) => request.post('/approval/reject', { id, remark })
export const batchApprove = (ids) => request.post('/approval/batch-approve', { ids, remark: '批量通过' })
export const batchReject = (ids, remark) => request.post('/approval/batch-reject', { ids, remark })
export const withdrawApproval = (type, id) => request.delete(`/approval/withdraw/${type}/${id}`)
export const submitApproval = (data) => request.post('/approval/submit', data)
export const getApprovalWorkflows = () => request.get('/approval/workflows')
export const updateApprovalWorkflow = (data) => request.post('/approval/workflows/update', data)
export const saveApprovalWorkflow = (data) => request.post('/approval/workflows', data)
export const deleteApprovalWorkflow = (id) => request.delete(`/approval/workflows/${id}`)

// ============ 邮件管理 ============
export const getEmailList = (params) => request.get('/email/list', { params })
export const sendEmail = (data) => request.post('/email/send', data)
export const getEmailAccounts = () => request.get('/email/accounts')
export const addEmailAccount = (data) => request.post('/email/accounts/add', data)
export const updateEmailAccount = (data) => request.post('/email/accounts/update', data)
export const deleteEmailAccount = (id) => request.post('/email/accounts/delete', { id })
export const syncEmails = () => request.post('/email/sync')
export const getEmailStats = () => request.get('/email/stats/overview')
export const markEmailRead = (id) => request.put(`/email/${id}/read`)
export const getEmailDetail = (id) => request.get(`/email/${id}`)
export const toggleEmailStar = (id) => request.put(`/email/${id}/star`)
export const linkCustomerToEmail = (id, customerId) => request.post(`/email/${id}/link-customer`, { customer_id: customerId })
export const testEmailAccount = (id) => request.post(`/email/account/${id}/test`)

// ============ 知识库 ============
export const getKnowledgeList = (params) => request.get('/knowledge/list', { params })
export const addKnowledge = (data) => request.post('/knowledge/add', data)
export const updateKnowledge = (data) => request.post('/knowledge/update', data)
export const deleteKnowledge = (id) => request.post('/knowledge/delete', { id })
export const getKnowledgeScripts = (params) => request.get('/knowledge/scripts', { params })
export const addKnowledgeScript = (data) => request.post('/knowledge/scripts/add', data)
export const updateKnowledgeScript = (data) => request.post('/knowledge/scripts/update', data)
export const deleteKnowledgeScript = (id) => request.post('/knowledge/scripts/delete', { id })
export const getKnowledgeFaqs = (params) => request.get('/knowledge/faqs', { params })
export const addKnowledgeFaq = (data) => request.post('/knowledge/faqs/add', data)
export const updateKnowledgeFaq = (data) => request.post('/knowledge/faqs/update', data)
export const deleteKnowledgeFaq = (id) => request.post('/knowledge/faqs/delete', { id })
export const getKnowledgeStats = () => request.get('/knowledge/stats')
export const getKnowledgeScript = (id) => request.get(`/knowledge/scripts/${id}`)
export const getKnowledgeScriptsScenes = () => request.get('/knowledge/scripts-meta/scenes')
export const getKnowledgeFaqsCategories = () => request.get('/knowledge/faqs-meta/categories')
export const getKnowledgeProducts = (params) => request.get('/knowledge/products', { params })
export const getKnowledgeProductsCategories = () => request.get('/knowledge/products-meta/categories')
export const addKnowledgeProduct = (data) => request.post('/knowledge/products', data)
export const updateKnowledgeProduct = (id, data) => request.put(`/knowledge/products/${id}`, data)
export const deleteKnowledgeProduct = (id) => request.delete(`/knowledge/products/${id}`)
export const getKnowledgeDocuments = (params) => request.get('/knowledge/documents', { params })
export const addKnowledgeDocument = (data, config) => request.post('/knowledge/documents', data, config)
export const updateKnowledgeDocument = (id, data) => request.put(`/knowledge/documents/${id}`, data)
export const deleteKnowledgeDocument = (id) => request.delete(`/knowledge/documents/${id}`)

// ============ AI助手 ============
export const getAiSuggestions = (params) => request.get(`/ai/suggestions${params || ''}`)
export const generateAiSuggestions = () => request.post('/ai/generate-suggestions')
export const aiSuggestionFeedback = (data) => request.post('/ai/suggestion/feedback', data)
export const aiQuery = (data, config) => request.post('/ai/query', data, config)
export const aiChat = (data, config) => request.post('/ai/chat', data, config)
export const getAiStatus = () => request.get('/ai/status')

// ============ 日程管理 ============
export const getCalendarEvents = (params) => request.get('/calendar/events', { params })
export const addCalendarEvent = (data) => request.post('/calendar/add', data)
export const updateCalendarEvent = (data) => request.post('/calendar/update', data)
export const deleteCalendarEvent = (id) => request.post('/calendar/delete', { id })

// ============ 提醒/通知 ============
export const getNotifications = (params) => request.get('/reminder/notifications', { params })
export const markNotificationRead = (id) => request.post('/reminder/notification-read', { id })
export const markAllRead = () => request.post('/reminder/mark-all-read')
export const getReminderCenter = () => request.get('/reminder/center')
export const getPaymentOverdue = () => request.get('/reminder/payment-overdue')
export const getMyReminders = () => request.get('/reminder/my-reminders')

// ============ 全局搜索 ============
export const globalSearch = (keyword) => request.get('/search/global', { params: { keyword } })

// ============ 回收站 ============
export const getRecycleList = (params) => request.post('/recycle/list', params)
export const restoreRecycle = (data) => request.post('/recycle/restore', data)
export const permanentDelete = (data) => request.post('/recycle/permanent-delete', data)

// ============ 满意度调查 ============
export const getSurveyTemplates = () => request.get('/survey/templates')
export const saveSurveyTemplate = (data) => request.post('/survey/templates', data)
export const deleteSurveyTemplate = (id) => request.delete(`/survey/templates/${id}`)
export const getSurveyCampaigns = () => request.get('/survey/campaigns')
export const saveSurveyCampaign = (data) => request.post('/survey/campaigns', data)
export const getSurveyAnalytics = (id) => request.get(`/survey/analytics/${id}`)
export const getCampaignDetail = (id) => request.get(`/survey/campaigns/${id}`)
export const getCampaignResponses = (id, params) => request.get(`/survey/campaigns/${id}/responses`, { params })
export const startCampaign = (id) => request.post(`/survey/campaigns/${id}/start`)
export const closeCampaign = (id) => request.post(`/survey/campaigns/${id}/close`)
export const getSurveyCampaign = (id) => request.get(`/survey/campaigns/${id}`)
export const submitSurveyResponse = (campaignId, data) => request.post(`/survey/respond/${campaignId}`, data)

// ============ 社媒沟通 ============
export const getSocialRecords = (params) => request.get('/social/records', { params })
export const saveSocialRecord = (data) => request.post('/social/records', data)
export const getSocialStats = () => request.get('/social/stats')
export const deleteSocialRecord = (id) => request.delete(`/social/records/${id}`)

// ============ 竞品分析 ============
export const getCompetitorList = (params) => request.post('/competitor/list', params)
export const getCompetitorDetail = (id) => request.get(`/competitor/detail/${id}`)
export const addCompetitor = (data) => request.post('/competitor/add', data)
export const updateCompetitor = (data) => request.post('/competitor/update', data)
export const deleteCompetitor = (id) => request.post('/competitor/delete', { id })
export const addCompetitorEncounter = (data) => request.post('/competitor/encounter/add', data)
export const addCompetitorIntel = (data) => request.post('/competitor/intel/add', data)
export const getCompetitorAnalysis = () => request.get('/competitor/analysis/overview')
export const getCompetitorEncounters = (id) => request.get(`/competitor/${id}/encounters`)
export const getCompetitorIntel = (id) => request.get(`/competitor/${id}/intel`)
export const deleteCompetitorEncounter = (id) => request.delete(`/competitor/encounters/${id}`)
export const deleteCompetitorIntel = (id) => request.delete(`/competitor/intel/${id}`)

// ============ 自动化 ============
export const getWorkflows = () => request.get('/automation/workflows')
export const saveWorkflow = (data) => request.post('/automation/workflows', data)
export const executeWorkflow = (id) => request.post('/automation/workflows/execute', { id })
export const getWorkflowLogs = (id) => request.get('/automation/workflows/logs', { params: { id } })
export const toggleWorkflow = (id) => request.post(`/automation/workflows/${id}/toggle`)
export const deleteWorkflow = (id) => request.delete(`/automation/workflows/${id}`)
export const getSmartReminders = () => request.get('/automation/smart-reminders')
export const saveSmartReminder = (data) => request.post('/automation/smart-reminders', data)
export const runSmartReminder = (id) => request.post('/automation/smart-reminders/run', { id })
export const getPendingReminders = () => request.get('/automation/smart-reminders/pending')
export const deleteSmartReminder = (id) => request.delete(`/automation/smart-reminders/${id}`)
export const markReminderSeen = (id) => request.put(`/automation/smart-reminders/log/${id}/seen`)
export const getAutomationAssignRules = () => request.get('/automation/assign-rules')
export const saveAutomationAssignRule = (data) => request.post('/automation/assign-rules', data)
export const applyAutomationAssignRule = (id) => request.post('/automation/assign-rules/apply', { id })
export const deleteAutomationAssignRule = (id) => request.delete(`/automation/assign-rules/${id}`)
