-- ============================================================
-- N-05 verify: ci-missing-tables.sql 91 段执行后置校验
-- ============================================================
-- ⚠ AUTO-GENERATED by scripts/build-n05-verify.py
--    不要手工修改本文件; 改 deploy/ci-missing-tables.sql 后
--    重跑 python scripts/build-n05-verify.py 重新生成。
-- ============================================================
-- 背景:91 段 PREPARE/EXECUTE 遇错时(1060/1062/1265),mysql client
--       默认继续执行并退出 0,导致"看似建好实际缺约束/列/索引"。
-- 方案:用 information_schema 重放每段的 WHERE 条件,与期望值对照。
--       不达标则由调用脚本 scripts/verify-ci-missing-tables.sh 决定 exit 1。
-- 设计:不创建 TEMP 表(MEMORY engine 二次引用触发 1137),
--       改用一个嵌套 SELECT + UNION ALL 一次输出明细与汇总。
-- 由 .github/workflows/ci.yml 在 apply ci-missing-tables.sql 之后
--       单独 docker exec ... mysql < verify.sql 调用,顺序敏感。
-- 设计原则:每条探测的 expected 取自其段语义:
--   - ADD COL / ADD INDEX / CREATE INDEX / ADD UNIQUE:expected = 1 (段后存在)
--   - MODIFY (探测含 DATA_TYPE):expected = 0 (段后类型改了)
-- ============================================================

SELECT
  GROUP_CONCAT(
    CONCAT(tag, IF(pass=1, '=OK', CONCAT('=FAIL(want ', expected, ', got ', actual, ')')))
    ORDER BY tag SEPARATOR ' | '
  ) AS __n05_per_item,
  SUM(pass) AS __n05_passed,
  COUNT(*) AS __n05_total,
  SUM(IF(pass=0, 1, 0)) AS __n05_failed
FROM (
  SELECT '@is_int_status' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'status' AND DATA_TYPE = 'tinyint') AS actual, 0 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'status' AND DATA_TYPE = 'tinyint') = 0, 1, 0) AS pass
  UNION ALL
  SELECT '@has_must_pwd' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'must_change_password') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'must_change_password') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@has_pwd_ch' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'password_changed_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'password_changed_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_quote_id' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'quote_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'quote_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@idx_quote_id' AS tag, (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND INDEX_NAME = 'idx_contract_quote_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND INDEX_NAME = 'idx_contract_quote_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_is_plan' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'is_plan') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'is_plan') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_spid' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'source_plan_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'source_plan_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_pstatus' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'plan_status') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'plan_status') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_ftime' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'finish_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'finish_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_qt' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_quote' AND COLUMN_NAME = 'update_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_quote' AND COLUMN_NAME = 'update_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_ct' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'update_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'update_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_primary' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND COLUMN_NAME = 'is_primary') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND COLUMN_NAME = 'is_primary') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@idx_primary' AS tag, (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND INDEX_NAME = 'idx_contact_primary') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND INDEX_NAME = 'idx_contact_primary') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@uk_primary' AS tag, (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND INDEX_NAME = 'uk_contact_primary_per_customer') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND INDEX_NAME = 'uk_contact_primary_per_customer') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_olid' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'original_lead_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'original_lead_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@idx_olid' AS tag, (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND INDEX_NAME = 'idx_original_lead_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND INDEX_NAME = 'idx_original_lead_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_mcp' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'must_change_password') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'must_change_password') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_pca' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'password_changed_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'password_changed_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_pp_ct' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment_plan' AND COLUMN_NAME = 'create_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment_plan' AND COLUMN_NAME = 'create_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@col_pp_ut' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment_plan' AND COLUMN_NAME = 'update_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment_plan' AND COLUMN_NAME = 'update_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_3' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contact' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_4' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_5' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_6' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_product' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_product' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_7' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_quote' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_quote' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_8' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_9' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment_plan' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment_plan' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_10' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_payment' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_11' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c095_12' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_approval_workflow' AND COLUMN_NAME = 'is_demo') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_approval_workflow' AND COLUMN_NAME = 'is_demo') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'applicant_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'applicant_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'expected_amount') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'expected_amount') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_3' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'reason') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'reason') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_4' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'approved_by') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'approved_by') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_5' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'approved_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'approved_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_6' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'reject_reason') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'reject_reason') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_7' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'created_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'created_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_8' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'updated_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'updated_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_9' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'comparison_no') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'comparison_no') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_10' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'product_name') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'product_name') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_11' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'quantity') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'quantity') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_12' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'unit') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'unit') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_13' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'selected_supplier_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'selected_supplier_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_14' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'created_by') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'created_by') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_15' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'created_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'created_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_16' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'updated_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'updated_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_17' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison_item' AND COLUMN_NAME = 'payment_terms') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison_item' AND COLUMN_NAME = 'payment_terms') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_18' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison_item' AND COLUMN_NAME = 'created_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison_item' AND COLUMN_NAME = 'created_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_19' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_request' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_20' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c096_21' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison_item' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_purchase_comparison_item' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c097_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'business_status') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'business_status') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c097_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'pool_status' AND DATA_TYPE = 'tinyint') AS actual, 0 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'pool_status' AND DATA_TYPE = 'tinyint') = 0, 1, 0) AS pass
  UNION ALL
  SELECT '@c102_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'lost_reason') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'lost_reason') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c103_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'opportunity_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'opportunity_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c103_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'from_stage') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'from_stage') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c103_3' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'to_stage') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'to_stage') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c103_4' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'changed_by') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'changed_by') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c103_5' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'create_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity_stage_log' AND COLUMN_NAME = 'create_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c104_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'opportunity_no') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'opportunity_no') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c104_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'source_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND COLUMN_NAME = 'source_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c104_3' AS tag, (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND INDEX_NAME = 'uk_opportunity_no') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND INDEX_NAME = 'uk_opportunity_no') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c104_4' AS tag, (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND INDEX_NAME = 'idx_source_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_opportunity' AND INDEX_NAME = 'idx_source_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_attachment' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_attachment' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_competitor_encounter' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_competitor_encounter' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_3' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_competitor_intel' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_competitor_intel' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_4' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract_template' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract_template' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_5' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_currency' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_currency' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_6' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_email_account' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_email_account' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_7' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_product_price' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_product_price' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_8' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_score_rule' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_score_rule' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_9' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_social_contact' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_social_contact' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c090_10' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_tag' AND COLUMN_NAME = 'deleted_at') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_tag' AND COLUMN_NAME = 'deleted_at') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c070_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'old_status_int') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_customer' AND COLUMN_NAME = 'old_status_int') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c091_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_notification' AND COLUMN_NAME = 'link_url') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_notification' AND COLUMN_NAME = 'link_url') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c072_1' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'category') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'category') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c072_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'rule_name') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'rule_name') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c072_3' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'min_score') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'min_score') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c072_4' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'max_score') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'max_score') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c072_5' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'weight') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'weight') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c072_6' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'sort_order') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_scoring_rule' AND COLUMN_NAME = 'sort_order') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c091_2' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_contact' AND COLUMN_NAME = 'create_by') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_contact' AND COLUMN_NAME = 'create_by') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c091_3' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_contact' AND COLUMN_NAME = 'update_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_contact' AND COLUMN_NAME = 'update_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c091_4' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_qualification' AND COLUMN_NAME = 'create_by') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_qualification' AND COLUMN_NAME = 'create_by') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c091_5' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_qualification' AND COLUMN_NAME = 'update_time') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_supplier_qualification' AND COLUMN_NAME = 'update_time') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c107' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'approval_status') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'approval_status') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c108a' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'cancel_reason') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'cancel_reason') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c108b' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'cancel_action') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_contract' AND COLUMN_NAME = 'cancel_action') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@c109' AS tag, (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'opportunity_id') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND COLUMN_NAME = 'opportunity_id') = 1, 1, 0) AS pass
  UNION ALL
  SELECT '@i109' AS tag, (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND INDEX_NAME = 'idx_fu_opportunity') AS actual, 1 AS expected, IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'crm_follow_up' AND INDEX_NAME = 'idx_fu_opportunity') = 1, 1, 0) AS pass
) AS __n05_checklist
INTO @__n05_per_item, @__n05_passed, @__n05_total, @__n05_failed;

-- 输出明细(便于 CI 日志定位失败项)
SELECT @__n05_per_item AS `N-05_ITEM_REPORT`,
       @__n05_passed    AS `N-05_PASSED`,
       @__n05_total     AS `N-05_TOTAL`,
       @__n05_failed    AS `N-05_FAILED`;

-- 终态汇总:仅打印,不抛错(SIGNAL 不能在 PREPARE 协议中)
-- exit 决策交给调用脚本 scripts/verify-ci-missing-tables.sh
SELECT IF(@__n05_failed = 0,
          CONCAT('N-05 ALL PASS: ', @__n05_passed, '/', @__n05_total, ' invariants satisfied'),
          CONCAT('N-05 FAIL: ', @__n05_failed, '/', @__n05_total, ' invariants violated (see N-05_ITEM_REPORT above for details)'))
       AS `N-05_FINAL`;
