#!/usr/bin/env python3
# ============================================================
# scripts/build-n05-verify.py
# ============================================================
# 作用:读 deploy/ci-missing-tables.sql,提取 91 段 PREPARE 段内的
#       information_schema 探测语句(SET @xxx = (SELECT COUNT(*) FROM
#       information_schema.{COLUMNS|STATISTICS} WHERE ...)),生成
#       deploy/ci-missing-tables-verify.sql。
#
#       每个探测作为 verify 中的一项 invariant。
#       expected 按段语义判定:
#         - ADD COL/INDEX/UNIQUE/CREATE INDEX:expected = 1 (段后存在)
#         - MODIFY (探测含 DATA_TYPE):expected = 0 (段后类型变了)
#
# 用法:
#   python scripts/build-n05-verify.py
# 或
#   /usr/bin/env python3 scripts/build-n05-verify.py
#
# 输出:
#   deploy/ci-missing-tables-verify.sql (按 91 段生成的 verify 文件)
# ============================================================

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'deploy', 'ci-missing-tables.sql')
OUT = os.path.join(ROOT, 'deploy', 'ci-missing-tables-verify.sql')


def extract_detections(sql_text: str):
    """抓所有 SET @xxx = (SELECT COUNT(*) FROM information_schema.{V} WHERE ...)"""
    pattern = re.compile(
        r"SET @(\w+)\s*=\s*\(SELECT COUNT\(\*\) FROM information_schema\.(\w+)\s*\n"
        r"\s*WHERE\s*((?:[^;|\n]|\n(?!SET ))+?)\);",
        re.DOTALL,
    )
    detections = []
    for m in pattern.finditer(sql_text):
        tag = m.group(1)
        view = m.group(2)
        where_clean = ' '.join(m.group(3).split())
        # MODIFY 段探测条件含 DATA_TYPE → expected = 0 (段后类型改了)
        expected = 0 if 'DATA_TYPE' in where_clean else 1
        detections.append((tag, view, where_clean, expected))
    return detections


def render_verify(detections):
    header = '''-- ============================================================
-- N-05 verify: ci-missing-tables.sql 91 段执行后置校验
-- ============================================================
-- ⚠ AUTO-GENERATED by scripts/build-n05-verify.py
--    不要手工修改本文件; 改 deploy/ci-missing-tables.sql 后
--    重跑 python scripts/build-n05-verify.py 重新生成。
-- ============================================================
-- 背景:91 段 PREPARE/EXECUTE 遇错时(1060/1062/1265),mysql client
--       默认继续执行并退出 0,导致"看似建好实际缺约束/列/索引"。
-- 方案:用 information_schema 重放每段的 WHERE 条件,与期望值对照。
--       不达标则由调用脚本 scripts/verify-ci-missing-tables.sh 决定 exit 1。
-- 设计:不创建 TEMP 表(MEMORY engine 二次引用触发 1137),
--       改用一个嵌套 SELECT + UNION ALL 一次输出明细与汇总。
-- 由 .github/workflows/ci.yml 在 apply ci-missing-tables.sql 之后
--       单独 docker exec ... mysql < verify.sql 调用,顺序敏感。
-- 设计原则:每条探测的 expected 取自其段语义:
--   - ADD COL / ADD INDEX / CREATE INDEX / ADD UNIQUE:expected = 1 (段后存在)
--   - MODIFY (探测含 DATA_TYPE):expected = 0 (段后类型改了)
-- ============================================================

SELECT
  GROUP_CONCAT(
    CONCAT(tag, IF(pass=1, '=OK', CONCAT('=FAIL(want ', expected, ', got ', actual, ')')))
    ORDER BY tag SEPARATOR ' | '
  ) AS __n05_per_item,
  SUM(pass) AS __n05_passed,
  COUNT(*) AS __n05_total,
  SUM(IF(pass=0, 1, 0)) AS __n05_failed
FROM (
'''
    footer = ''') AS __n05_checklist
INTO @__n05_per_item, @__n05_passed, @__n05_total, @__n05_failed;

-- 输出明细(便于 CI 日志定位失败项)
SELECT @__n05_per_item AS `N-05_ITEM_REPORT`,
       @__n05_passed    AS `N-05_PASSED`,
       @__n05_total     AS `N-05_TOTAL`,
       @__n05_failed    AS `N-05_FAILED`;

-- 终态汇总:仅打印,不抛错(SIGNAL 不能在 PREPARE 协议中)
-- exit 决策交给调用脚本 scripts/verify-ci-missing-tables.sh
SELECT IF(@__n05_failed = 0,
          CONCAT('N-05 ALL PASS: ', @__n05_passed, '/', @__n05_total, ' invariants satisfied'),
          CONCAT('N-05 FAIL: ', @__n05_failed, '/', @__n05_total, ' invariants violated (see N-05_ITEM_REPORT above for details)'))
       AS `N-05_FINAL`;
'''
    parts = []
    for tag, view, where, expected in detections:
        sel = f"(SELECT COUNT(*) FROM information_schema.{view} WHERE {where})"
        parts.append(
            f"  SELECT '@{tag}' AS tag, {sel} AS actual, "
            f"{expected} AS expected, IF({sel} = {expected}, 1, 0) AS pass"
        )
    body = '\n  UNION ALL\n'.join(parts)
    return header + body + '\n' + footer


def main():
    if not os.path.exists(SRC):
        print(f"✗ {SRC} not found", file=sys.stderr)
        return 2
    with open(SRC, 'r', encoding='utf-8') as f:
        text = f.read()
    detections = extract_detections(text)
    n_modify = sum(1 for d in detections if d[3] == 0)
    print(f"探测段: {len(detections)} (含 DATA_TYPE 的 MODIFY 类 expected=0: {n_modify})")
    content = render_verify(detections)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(content)
    bytes_written = os.path.getsize(OUT)
    print(f"已写出 {OUT}: {bytes_written} bytes / {content.count(chr(10))} 行")
    return 0


if __name__ == '__main__':
    sys.exit(main())
